# Generated by Django 5.0 on 2024-01-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_remove_product_product_information_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
