# Generated by Django 4.2.9 on 2024-01-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_product_packing_cost_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_cost',
            field=models.IntegerField(null=True),
        ),
    ]
